services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sbt
    ports:
      - "5432:5432"
    volumes:
      - sbt_data:/var/lib/postgresql/data
volumes:
  sbt_data:
